// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrap() {
  return window['go']['main']['DesktopApp']['GetBootstrap']();
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ServeHTTP'](arg1, arg2);
}
