// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function GetBootstrap():Promise<main.DesktopBootstrap>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
